// sidebarstpls.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarstpls = {
    api: [
        {
            type: "autogenerated",
            dirName: ".",
        },
    ],
};

module.exports = sidebarstpls;
// sidebarstpls.ts