// sidebarstpls.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsproj = {
    api: [
        {
            type: "autogenerated",
            dirName: ".",
        },
    ],
};

module.exports = sidebarsproj;
// sidebarstpls.ts