// sidebarsquiz.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsquiz = {
  api: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebarsquiz;
// sidebarsquiz.ts
