// sidebarslabs.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarslabs = {
  api: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

module.exports = sidebarslabs;
// sidebarslabs.ts
