name: Deploy Docusaurus

on:
  # push:
  #   branches:
  #     - main # Runs every time you push code to main
  workflow_dispatch: # Allows you to run this manually from the "Actions" tab
  #schedule:
  #  - cron: '0 0 * * *' # Runs automatically every day at midnight UTC
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Pre-fetch Group Status
        run: node scripts/check-groups.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docusaurus
        run: npm run build
